---
title: "APTS Design of Experiments - Practical 2"
subtitle: "August 2018"
author: "Dave Woods (<D.Woods@southampton.ac.uk> ; <http://www.southampton.ac.uk/~davew>) <br> Statistical Sciences Research Institute, University of Southampton"
output: 
#beamer_presentation
#pdf_document:
  html_document:
    theme: null
    highlights: null
bibliography: ../notes/apts_doe.bib
#csl: american-statistical-association.csl
number_sections: true
---

\newcommand{\bx}{\boldsymbol{x}}
\newcommand{\btheta}{\boldsymbol{\theta}}
\newcommand{\bbeta}{\boldsymbol{\beta}}
\newcommand{\bvarepsilon}{\boldsymbol{\varepsilon}}
\newcommand{\by}{\boldsymbol{y}}
\newcommand{\rT}{\mathrm{T}}
\newcommand{\Var}{\operatorname{Var}}


<style>
pre {
  font-size: 15px;
}
</style>

```{r, echo=FALSE}
options(width=80)
library(knitr)
library(xtable)
set.seed(1)
knit_hooks$set(no.main = function(before, options, envir) {
    if (before) par(mar = c(4.1, 4.1, 1.1, 1.1), pty = "s")  # smaller margin on top
})
opts_chunk$set(echo=TRUE, warning=FALSE, message=FALSE)
```

In this practical session, you will use the <tt>acebayes</tt> package to investigate some aspects of (Bayesian) optimal design. Feel free to also use the practical sessions to understand and reproduce results from the notes.

<!-- pseudo-Bayesian design using optim-->
1\. **Bayesian $D$-optimal design using <tt>optim</tt>**  
Adapt the code from the notes to find locally $D$-optimal designs with $n=2$ runs for the Poisson regression model with linear predictor $\eta(x) = \beta_0 + \beta_1 x$ with the log link (log-linear regression).

Fix $\beta_0=0$ and find designs for $\beta_1 = 1, \ldots, 6$, restricting to $-1\le x\le 1$. For each design, plot the design points along with the expected response. There is a pattern in the optimal designs, can you identify it?

(Hint: there is a relationship between the first design point and $1/\beta_1$).

The <tt>acebayes</tt> package has a function <tt>aceglm</tt> that can find Bayesian optimal designs for generalised linear models. Read the help file, and the use the function to find a Bayesian $D$-optimal design when we assume $\beta_0 = 0$ and a uniform prior distribution for $\beta_1$ with support $[1,6]$.

**Important**: when using <tt>aceglm</tt> set $N2 = 0$ (otherwise it will result in a nasty crash!).

<!-- pseudo-Bayesian design using ace -->
2\. **Bayesian $D$-optimal design using <tt>acebayes</tt>**  
In the notes, we examine a compartmental model. A simplified version of this model is given by
$$
y_i \sim N\left(\mu(x_i\,;\,\btheta), \sigma^2\right)\,, 
$$
with
$$
\mu(x_i\,;\,\btheta) = \theta_3\left[\exp\left(-\theta_1 x\right) - \exp\left(-\theta_2 x\right)\right]\,.
$$
Use the <tt>acenlm</tt> function in <tt>acebayes</tt> to find a Bayesian $D$-optimal design with $n=18$ runs, assuming $x \in [0, 24]$. Assume uniform prior distributions for $\theta_1,\theta_2$:
$$
\theta_1 \sim U(0.01884, 0.09884);\qquad \theta_2 \sim U(0.298, 8.298)
$$
with $\theta_3 = 21.8$; see @GJS2009 and @OWA2017. Plot the optimal design and realisations from the model.

# References